### ISSUE TITLE
吃瓜群众的建议

### ISSUE THREAD

**Issue by weypro** [VoidmatrixHeathcliff/BacklightEngine#1]
应该给一个demo的链接，不然还得自己编译
坐等加入各种转场效果（图片和音乐）  
图片也应该是有一个hide而不仅仅是show  
要是能做到直接切换表情（头）、动作而不是切换整个立绘那就太好了（比如ddlc）

**Comment by VoidmatrixHeathcliff** [comment]
谢谢您的建议，由于架构原因，BacklightEngine作为自定义脚本解析实验性产品的寿命已经结束，后续可能不会再对此项目进行维护，如需进行AVG类游戏或更多类型的游戏开发，请关注[QGame游戏引擎](https://github.com/VoidmatrixHeathcliff/QGame)

**Comment by LaoshuBaby** [comment]
> 
> 
> 谢谢您的建议，由于架构原因，BacklightEngine作为自定义脚本解析实验性产品的寿命已经结束，后续可能不会再对此项目进行维护，如需进行AVG类游戏或更多类型的游戏开发，请关注[QGame游戏引擎](https://github.com/VoidmatrixHeathcliff/QGame)

所以BacklightEngine->QGame->EtherEngine之间，对于AVG的parser有没有变化呢？

**Comment by LaoshuBaby** [comment]
> 
> 
> 应该给一个demo的链接，不然还得自己编译
> 坐等加入各种转场效果（图片和音乐）
> 图片也应该是有一个hide而不仅仅是show
> 要是能做到直接切换表情（头）、动作而不是切换整个立绘那就太好了（比如ddlc）

[UniGal-Script 支持列表](https://github.com/Uni-Gal/UniGal-Script/blob/master/Readme/zh_CN/UniGal-supportlist.md)

【↑】这里面标记为```活跃```的引擎都是目前有一定用户基础的引擎，（本md起到了目录的作用，笑），这些都有较为完善的功能，不少引擎的文档和社区建设也比较好，如果真的要做AVG品类的游戏的话，用这些较为成熟的引擎会比较好一些

并且，站在投资未来，少欠技术债的角度，更推荐用较新的引擎。

**Comment by VoidmatrixHeathcliff** [comment]
> > 谢谢您的建议，由于架构原因，BacklightEngine作为自定义脚本解析实验性产品的寿命已经结束，后续可能不会再对此项目进行维护，如需进行AVG类游戏或更多类型的游戏开发，请关注[QGame游戏引擎](https://github.com/VoidmatrixHeathcliff/QGame)
> 
> 所以BacklightEngine->QGame->EtherEngine之间，对于AVG的parser有没有变化呢？

QGame和EtherEngine都是对于游戏底层接口的实现，并未搭建具体的游戏框架（到目前为止），后续在框架完成后将考虑合并进入UNIGal标准

**Comment by LaoshuBaby** [comment]
到时候需要帮忙的时候请尽管抓我~！ε=ε=ε=(~￣▽￣)~




------------------&nbsp;Original&nbsp;------------------
